apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: k8s-clubhouse-clone
build:
  artifacts:
    - image: bineetnaidu/clubhouse-auth
      context: services/auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/ingress.yaml
      - k8s/auth-pg-depl.yaml
      - k8s/auth-depl.yaml
